### ISSUE TITLE
Additional debug tools in default image, e.g. strace

### ISSUE THREAD

**Issue by mikehaller** [eclipse-leda/leda-distro#111]
During onboarding of Leda distro to new hardware devices, such as the Jacinto eval kit, it's necessary to go through a couple of low-level functionality: boot process, filesystem layouts, RAUC integration etc.

Often, it's not clear when some tools have problems, e.g. "fw_printenv" not finding the correct config file and problems like that.

Tools like `strace` would be helpful to have on the default full image (sdv-image-full), to be able to debug the system. Maybe a "-dev" feature toggle. The alternative option to install these tools as a container is not practical, as the state of the system integration is very early and at that point in time, the container runtime may not even be functional yet.

**Comment by d-s-e** [comment]
The full image is used for hacking anyway, so I don't think the feature toggle is necessary.
Installing just `strace`is easy, which other tools do you need?

Usually `EXTRA_IMAGE_FEATURES:append = " tools-debug"` is used for that, but this will fail due to the GPLv3 restriction.

**Comment by vasilvas99** [comment]
Strace was added in https://github.com/eclipse-leda/meta-leda/pull/202 , its small enough (~2MBs). Maybe we can also add file and ldd and this should be more than enough for basic on-device debugging of binaries?
