### ISSUE TITLE
Cloud connector stopped working

### ISSUE THREAD

**Issue by stlachev** [eclipse-leda/leda-distro#158]
[Cloudconnector](https://github.com/eclipse-leda/leda-contrib-cloud-connector) stopped working, because expiration of [iothub.crt](https://github.com/eclipse-leda/leda-contrib-cloud-connector/blob/main/resources/iothub.crt)

**Comment by vasilvas99** [comment]
Closing because it's a duplicate issue as: https://github.com/eclipse-leda/leda-distro/issues/116 

And moving the new information there as a comment.
