### ISSUE TITLE
Integrate Eclipse Kuksa.VAL - GPS Feeder

### ISSUE THREAD

**Issue by mikehaller** [eclipse-leda/leda-distro#20]
The GPS feeder of Kuksa provides GPS coordinates as Vehicle Signal in the Data Broker according to the Vehicle Signal Specification.
The GPS feeder uses a locally running gpsd, which needs to be preinstalled into the Leda distribution.

Default configuration will not work out of the box, as the configuration depends on the specific hardware attached to the device. On raspi, that may be a GPS connected via USB or serial. On qemu, we may want to use a GPS faker application to simulate the location.

**Comment by mikehaller** [comment]
This is has been blocked due to compilation errors. Needs investigation.

**Comment by mikehaller** [comment]
For the default configuration, Leda should use a "sane default".

In case of [gpsd](https://wiki.ubuntuusers.de/gpsd/), it seems we should be using `/dev/ttyUSB0` as default, as it supports most of the GPS devices out of the box.

**Comment by d-s-e** [comment]
According to [your comment here](https://github.com/eclipse-leda/leda-distro/issues/128#issuecomment-1625003195) `gpsd` should run inside the container and not on the host, correct?

**Comment by mikehaller** [comment]
I would say yes, as it is an optional feature from an SDV point of view, and it's easier to configure at runtime via the container runtime.

Since our current supported HW platform is not static (eg raspi gps module can be attached and is not built in)

But i think it would be acceptable tradeoff to have gpsd preinstalled natively, once we know how to dynamically change the config at runtime through Desired State. Since that is conceptually not clear yet.

So with sane default for Raspi, we could just start by preinstalling it on the sdv-image packagegroup additions.

We could use this issue also for testing out the bitbake-built container images.

wdyt?
