### ISSUE TITLE
git submodules are not available

### ISSUE THREAD

**Issue by phongt** [eclipse-leda/leda-distro#3]
There is  `meta-sdv` in [.gitmodule](https://github.com/eclipse-leda/leda-distro/blob/main/.gitmodules#L27) can not find.

```console
$ git clone https://github.com/eclipse-leda/leda-distro.git
$ cd leda-distro
$ git submodule init
$ git submodule update
```
 After executing `git submodule update` can not find any git submodule (eg: poky, meta-virtualization...). Look like missing commit & push the git submodule directory

**Comment by mikehaller** [comment]
Thanks for bringing this up.
We're currently migrating to kas, which does the submodule handling automatically.

**Comment by phongt** [comment]
cool!.I can build with instruction in [README.md](https://github.com/eclipse-leda/leda-distro/blob/main/kas/README.md)
