### ISSUE TITLE
Include a larger subset of the python 3.10 standard library in sdv-image-full

### ISSUE THREAD

**Issue by vasilvas99** [eclipse-leda/leda-distro#69]
**Is your feature request related to a problem? Please describe.**
By default sdv-image-all installs the basic poky python package, which includes a very minimal subset of the python standard library. While nice for the final image size, this limits what scripts running natively (outside of containers with full python installations) on the image can do (e.g. random, pydoc, socket are missing).

**Describe the solution you'd like**
According to [How to work with Python applications and modules in Yocto Project](https://hub.mender.io/t/how-to-work-with-python-applications-and-modules-in-yocto-project/1135) the full python standard library can be installed by installing the `python3-modules` package. It however, depends on GPL3.0-licensed packages which is incompatible with the Leda-distro license (Apache-2.0).

**Describe alternatives you've considered**
 - A very useful subset of the python standard library, that does not depend on GPL3.0-licensed components can be installed through `python3-misc` (includes random and socket for example)
 - A `.bbappend` which excludes GPL3.0-licensed from the `python3-modules` package can be prepared. (best solution)

**Additional context**
None

**Comment by mikehaller** [comment]
An alternative solution may be to prepare a container with a full python installation and run it on demand.

By extending sdv-ctr-exec so that it would also pull and create the containers, similar to "docker run"

I assume there are already docker containers with python for various use cases.

Also agreeing to the idea of having at least the basic set of std libs natively installed would make it simpler to use during hackathons and ad-hoc experiments.

**Comment by d-s-e** [comment]
I would expect to have the python standard library available, if there is python on a system, especially if it is intended to be used for hacking and experimenting.
The only GPLv3-licensed blocker for having the full stdlib installed, is `gdbm`, which is easy to remove.

**Comment by d-s-e** [comment]
fixed with https://github.com/eclipse-leda/meta-leda/commit/c24e93599670914063ced42879b0d8f1743f9442
